Mango.Web/Controllers/AuthController.cs
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using AspNetCoreHero.ToastNotification.Abstractions;
using Mango.Web.Models;
using Mango.Web.Models.AuthDto;
using Mango.Web.Service.IService;
using Mango.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        private readonly INotyfService _notyf;

        public AuthController(
            IAuthService authService,
            INotyfService notyfService,
            ITokenProvider tokenProvider)
        {
            _authService = authService;
            _notyf = notyfService;
            _tokenProvider = tokenProvider;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new();
            return View(loginRequestDto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDto obj)
        {
            var responseDto =await _authService.LoginAsync(obj);
            if(responseDto != null && responseDto.IsSuccess)
            {
                var loginResponseDto= JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result)!)!;
                _tokenProvider.SetToken(loginResponseDto.Token);
                await SignInUser(loginResponseDto);
                return RedirectToAction("Index","Home");
            }
            else
            {
                ModelState.AddModelError("CustomerError", responseDto!.Message);
                return View(obj);
            }
        }
        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text = SD.RoleAdmin,Value = SD.RoleAdmin},
                new SelectListItem{Text = SD.RoleCustomer,Value = SD.RoleCustomer}
            };
            ViewBag.RoleList= roleList;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationRequestDto obj)
        {
            ResponseDto? result = await _authService!.RegisterAsync(obj);
            ResponseDto? assignRole;
            if (result!=null&&result.IsSuccess)
            {
                if (string.IsNullOrEmpty(obj.Role))
                {
                    obj.Role= SD.RoleCustomer;
                }

                assignRole = await _authService.AssignRoleAsync(obj)!;
                if (assignRole != null&&assignRole.IsSuccess)
                {
                    _notyf.Success("Registration Successful");
                }

                return RedirectToAction(nameof(Login));
            }
            else
            {
                ModelState.AddModelError("Error",result!.Message);
            }
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text = SD.RoleAdmin,Value = SD.RoleAdmin},
                new SelectListItem{Text = SD.RoleCustomer,Value = SD.RoleCustomer}
            };
            ViewBag.RoleList = roleList;
            return View(obj);
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index","Home");
        }

        public async Task SignInUser(LoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwt = handler.ReadJwtToken(model.Token);

            var claims = jwt.Claims.Select(c => new Claim(c.Type, c.Value)).ToList();
            claims.Add(new Claim(
                ClaimTypes.Name, 
                jwt.Claims.FirstOrDefault(x => x.Type == "name")?.Value!)); // Add 'name' claim

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }

    }
}

Mango.Web/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly INotyfService _notyf;

        public CartController(ICartService cartService, INotyfService notyfService)
        {
            _cartService = cartService;
            _notyf = notyfService;
        }
        [Authorize]
        public async Task<IActionResult> CartIndex()
        {
            return View(await LoadCartDtoBasedOnLoggedInUser());
        }

        private async Task<CartDto?> LoadCartDtoBasedOnLoggedInUser()
        {
            var userId = User.Claims.
                Where(u => u.Type == JwtRegisteredClaimNames.Sub)
                ?.FirstOrDefault()?.Value;
            var response = await _cartService.GetCartByUserIdAsync(userId!);
            if (response!=null && response.IsSuccess)
            {
                var cartDto = JsonConvert.DeserializeObject<CartDto>(Convert.ToString(response.Result)!);
                return cartDto;
            }

            return new CartDto();
        }

        public async Task<IActionResult> Remove(int cartDetailsId)
        {
            var userId = User.Claims.
                Where(u => u.Type == JwtRegisteredClaimNames.Sub)
                ?.FirstOrDefault()?.Value;
            var response = await _cartService.RemoveFromCartAsync(cartDetailsId);
            if(response != null && response.IsSuccess)
            {
                 _notyf.Success("Cart update successfully");
                return RedirectToAction(nameof(CartIndex));
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ApplyCoupon(CartDto cartDto)
        {
            var response = await _cartService.ApplyCouponAsync(cartDto);
            if (response != null && response.IsSuccess)
            {
                _notyf.Success("Cart update successfully");
                return RedirectToAction(nameof(CartIndex));
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RemoveCoupon(CartDto cartDto)
        {
            cartDto.CartHeader.CouponCode = "";
            var response = await _cartService.ApplyCouponAsync(cartDto);
            if (response != null && response.IsSuccess)
            {
                _notyf.Success("Cart update successfully");
                return RedirectToAction(nameof(CartIndex));
            }

            return View();
        }
    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Net;

namespace Mango.Web.Controllers
{
    
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        private readonly INotyfService _notyf;

        public CouponController(ICouponService couponService, INotyfService notyfService)
        {
            _couponService = couponService;
            _notyf = notyfService;
        }

        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDto>? list = new();
            var response = await _couponService.GetAllCouponsAsync();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result)!);
            }
            else
            {
                if (response!.StatusCode == HttpStatusCode.Forbidden)
                {
                    _notyf.Error(response!.Message, 5);
                    return RedirectToAction("AccessDenied", "Home");
                }
                else if(response.StatusCode== HttpStatusCode.Unauthorized)
                {
                    _notyf.Error(response!.Message, 5);
                    return RedirectToAction("Login", "Auth");
                }
            }
            return View(list);
        }

        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CouponCreate(CouponDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _couponService.CreateCouponAsync(model);
                if (response != null && response.IsSuccess)
                {
                    _notyf.Success("Coupon Created Successfully");
                    return RedirectToAction(nameof(CouponIndex));
                }
                else
                {
                    _notyf.Error(response!.Message);
                }
            }

            return View(model);
        }
        public async Task<IActionResult> CouponDelete(int couponId)
        {
            ResponseDto? response = await _couponService.GetCouponByIdAsync(couponId);
                if(response != null && response.IsSuccess)
                {
                CouponDto? model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result)!);
                return View(model);
                }
                else
                {
                    _notyf.Error(response!.Message);
                }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDto model)
        {
            ResponseDto? response = await _couponService.DeleteCouponAsync(model.CouponId);
            if (response != null && response.IsSuccess)
            {
                _notyf.Success("Coupon Deleted Successfully");
                return RedirectToAction(nameof(CouponIndex));
            }
            else
            {
                _notyf.Error(response!.Message);
            }
            return View(model);
        }

    }
}

Mango.Web/Controllers/ProductController.cs
using System.Net;
using AspNetCoreHero.ToastNotification.Abstractions;
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Mango.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly INotyfService _notyf;

        public ProductController(IProductService productService, INotyfService notyf)
        {
            _productService = productService;
            _notyf = notyf;
        }
        public async Task<IActionResult> ProductIndex()
        {
            List<ProductDto>? list = new();
            var response = await _productService.GetAllProductsAsync();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result)!);
            }
            else
            {
                if (response!.StatusCode == HttpStatusCode.Forbidden)
                {
                    _notyf.Error(response!.Message, 5);
                    return RedirectToAction("AccessDenied", "Home");
                }
                else if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    _notyf.Error(response!.Message, 5);
                    return RedirectToAction("Login", "Auth");
                }
            }
            return View(list);
        }

        public async Task<IActionResult> ProductCreate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProductCreate(ProductDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _productService.CreateProductAsync(model);
                if (response != null && response.IsSuccess)
                {
                    _notyf.Success("Product Created Successfully");
                    return RedirectToAction(nameof(ProductIndex));
                }
                else
                {
                    _notyf.Error(response!.Message);
                }
            }

            return View(model);
        }
        public async Task<IActionResult> ProductDelete(int productId)
        {
            ResponseDto? response = await _productService.GetProductByIdAsync(productId);
            if (response != null && response.IsSuccess)
            {
                ProductDto? model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(response.Result)!);
                return View(model);
            }
            else
            {
                _notyf.Error(response!.Message);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProductDelete(ProductDto model)
        {
            ResponseDto? response = await _productService.DeleteProductAsync(model.ProductId);
            if (response != null && response.IsSuccess)
            {
                _notyf.Success("Product Deleted Successfully");
                return RedirectToAction(nameof(ProductIndex));
            }
            else
            {
                _notyf.Error(response!.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> ProductEdit(int productId)
        {
            ResponseDto? response = await _productService.GetProductByIdAsync(productId);
            if (response != null && response.IsSuccess)
            {
                ProductDto? model = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(response.Result)!);
                return View(model);
            }
            else
            {
                _notyf.Error(response!.Message);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> ProductEdit(ProductDto productDto)
        {
            ResponseDto? response = await _productService.UpdateProductAsync(productDto);
            if (response != null && response.IsSuccess)
            {
                _notyf.Success("Product Updated Successfully");
                return RedirectToAction(nameof(ProductIndex));
            }
            else
            {
                _notyf.Error(response!.Message);
            }
            return View(productDto);
        }
    }
}

Mango.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/bootstrap-icons/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mango.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["action"]?.ToString() == "Index" ? "active" : "")" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(ViewContext.RouteData.Values["action"]?.ToString() == "Privacy" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link @(ViewContext.RouteData.Values["action"]?.ToString() == "Privacy#" ? "active" : "") dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Product</a></li>
                                <li><hr class="dropdown-divider"></li>

                            </ul>
                        </li>
                        <li><a class="dropdown-item" asp-controller="Cart" asp-action="CartIndex">
                            &nbsp; <i class="bi bi-cart"></i>&nbsp;
                        </a></li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">
                                    <i class="bi bi-box-arrow-in-right"></i> Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">
                                    <i class="bi bi-person-plus"></i> Register
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="bi bi-person-fill" style="color: orangered;"></i>
                                    Hello @User.Identity.Name
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">
                                    <i class="bi bi-box-arrow-right"></i> Logout
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark" data-bs-theme="dark">
        <div class="text-center">
            <span style="color:darkgray"> ASP .NET © Project | Made with <i class="bi bi-heart-fill"></i> By Al Nuaimi</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
@await Component.InvokeAsync("Notyf")
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>